[package]
name = "mpc_test_app"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.7"
futures = "0.3.19"
mpc = { path = "../mpc" }
mpc_flow = { path = "../mpc_flow" }
ndarray = "0.15.4"
rand = "0.8.4"
tokio = { version = "1.15.0", features = ["full"] }
