[package]
name = "mpc"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.52"
futures = "0.3.19"
num-traits = "0.2.14"
rand = "0.8.4"
tokio = { version = "1.15.0", features = ["full"] }
