[package]
name = "mpc"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.52"
ff = { version = "0.11", features = ["derive"] }
futures = "0.3.19"
rand = { version = "0.8.4", features = ["small_rng"] }
tokio = { version = "1.15.0", features = ["full"] }
